# Site settings
title: Felix Wolff
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://flxw.github.io" # the base hostname & protocol for your site
timezone: Europe/Berlin
language: en-gb

twitter_username: zwitscherwolff
github_username:  jekyll
linkedin_url: http://de.linkedin.com/pub/felix-wolff/77/756/b66

author: "Felix Wolff"
speciality: "IT-Systems Engineer"
place: "Berlin &amp; Brisbane"

# Build settings
markdown: rdiscount
