# Site settings
title: "Felix Wolff"
description: On stuff that I think can help others
author: Felix Wolff
url: "https://flxw.de" # the base hostname & protocol for your site

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

