# Site settings
title: Felix Wolff
name:  Felix Wolff
description: Personal landing page for Felix Wolff, software engineer with diverse interests
baseurl: ""
url: "http://flxw.de"
timezone: Europe/Berlin
language: en-gb

twitter_username: zwitscherwolff
github_username:  flxw
linkedin_url: http://de.linkedin.com/pub/felix-wolff/77/756/b66

author: "Felix Wolff"
speciality: "IT-Systems Engineer"
place: "Berlin &amp; Brisbane"

# Build settings
markdown: rdiscount
