# Site settings
title: "flxw.de"
description: On stuff that might help others
author: Felix Wolff
url: "https://flxw.de"

# Build settings
include: [_pages]
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

